### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by ajpyoung** [chill117/mysql-connection-manager#6]
Sorry if this isn't the correct location to ask this question, but I'm wondering if the mysql-connection-manager supports SSL Certificates like node-mysql?

ssl={
	ca : fs.readFileSync( '/certificates/MySQL/server-ca.pem'),
	key : fs.readFileSync( '/certificates/MySQL/client-key.pem'),
	cert : fs.readFileSync( '/certificates/MySQL/client-cert.pem')
}

**Comment by chill117** [comment]
Yes, you can pass your [SSL options](https://github.com/felixge/node-mysql#ssl-options) like this:
```js
var MySQLConnectionManager = require('mysql-connection-manager');

var options = {
    ssl: {
        ca : fs.readFileSync( '/certificates/MySQL/server-ca.pem')
    }
};

var manager = new MySQLConnectionManager(options);
```

The options you pass to this module, are passed directly to `mysql.createConnection(options)` (or `mysql.createPool(options)` if using pooling).
