### ISSUE TITLE
[enhancement] Accept connection pool in constructor

### ISSUE THREAD

**Issue by fcarreiro** [chill117/mysql-connection-manager#8]
I'm actually coming here from `express-mysql-session`. It would be useful if we could pass an already-created connection pool to the constructor instead of having it created by the manager. 
```javascript
var manager = new MySQLConnectionManager(options, pool);
```
For example, in my application I already handle all the pool creation and reconnection myself.

Would you find this enhancement interesting? I might be able to have some time to implement it myself. In that case, would it be possible to merge and release a new version relatively quickly?

Thanks!

**Comment by chill117** [comment]
@fcarreiro I think this is already possible (see [here](https://github.com/chill117/mysql-connection-manager#how-to-use)). If that doesn't work for your use case, I am of course open to pull requests. It usually takes me a few days to find some time available to review and merge a PR.

**Comment by fcarreiro** [comment]
Dear @chill117, for the moment I "fixed" it by actually using `mysql-connection-manager` in my app (instead of my own connection management routines), and simply passing the `mysql-connection-manager` object.

I was originally avoiding to use `mysql-connection-manager` because the way it handles reconnections makes me a bit nervous. Namely, copying the key-values of the new connection object to the old one. I understand why you need to do this (I have been there when trying to implement a manager myself), and I see that it works in practice. It just makes me feel that it may "miss" something intrinsic from the new object :)

In any case, I'll close this issue for the moment. Thanks for the attention!
